### ISSUE TITLE
Task & Implementation

### ISSUE THREAD

**Issue by Suntrie** [uncleanw/consoleCut#1]
С forbids, насколько я понимаю, у Вас, в итоге, все вроде получилось.
Общая просьба: пожалуйста, выкладывайте на гит только те версии, которые собираются (если не было специальной договоренности). Для сохранения промежуточного состояния кода можно использовать локальные коммиты (без пушей).

1.  Ключ -o по заданию, вроде,  обязательным не является - а у Вас пока наоборот, а вот 'c' или 'w' - должны быть required (на уровне автоматизированного парсинга это, скорее всего, сделать не удастся, но вручную стоит отследить);

2. Для inputName/ outputName на самом деле [можно сразу заводить файлы](https://github.com/kohsuke/args4j/blob/master/args4j/examples/SampleMain.java);

3. "org.kohsuke.args4j.CmdLineException: "-5" недействительная опция" -при попытке подавать числа, начинающиеся со знака "минус" библиотека попытается распознать их как опции - и ничего хорошего из этого не выйдет. Workaround: "Если нет — имеет смысл ввести в качестве имени -r (то есть - превратиться из Argument в Option), например, -r -5 или -r 6-7, дальше парсите, например, проверяете формат и проходите сплитом. Разместить обработчик диапазона, который на его основе сформирует числовые значения,  можно внутри функции — см. https://args4j.kohsuke.org/sample.html."
Последнее может выглядеть как, например:
```
@Option(required = true, metaVar = "range", name="-r", usage = "range of cutting")
    private void range(String range){
        this.k=-Integer.parseInt(range);
    };
```
- здесь рассмотрен только один из возможных случаев корректного введения диапазона.

4. Стоит быть осторожнее с форматом - возможно, проще всего его изначально проверить Regexp-ом. Пока легко получить ArrayOutOfBoundsException - пользователь, по умолчанию, играет против Вас;

5. Конструктор CutterLauncher у Вас пока пустой - Вы все поля заполняете в методе launch. Вызов парсера, etc, в принципе,  можно вынести в конструктор, но тогда дополнительно надо будет пробрасывать исключение (или отдельно делать catch в Main, а не в новом конструкторе для уже выбрасываемого): чтобы на уровне программы понять, что после неудачного вызова конструктора ее выполнение пора заканчивать;

6. Main и CutterLauncher лучше разнести - в Main Вы просто можете создавать объект  CutterLauncher, а в нем самом (в его конструкторе) заполнять поля, и в зависимости от заполненных полей определять выполняемые действия. Так лучше, потому что сам main - скорее процедурный, не совсем ООП. Его лучше держать отдельно. Тогда как класс = данные + методы работы с ними;

7. лаунчер - это не метод интерфейса или абстрактного класса, который Вы обязаны переписывать для применения библиотеки. Это просто название метода, в который авторами примера была вынесена логика инициализации;

8. Charset-ы можно использовать по умолчанию;

9. Структурно в cutting все еще много копипасты (его вроде можно в два раза сократить);

10. Относительно записи в файл - можно попробовать [так](https://www.geeksforgeeks.org/redirecting-system-out-println-output-to-a-file-in-java/), если я правильно поняла Ваш вопрос.

**Comment by Houston613** [comment]
после огромной стены текста, которую я вам скинул, я вроде разобрался, но все равно не уверен. 
Тесты не работают. Я вообще не знаю, будет ли все что я написал  работать, но я залью на гит, может вы что-то скажете.)
1)у меня архитектура немного отличается от той, что вы предлагали. Допустима ли она?
2)range нигде не вызывается, но ето норма?  он все равно будет работать при запуске парсера?
3)везде ли я добавил try catch? я, скорее всего, не очень в них разобрался, поэтому испытываю затруднения
4) в классе обработки файлов правильно ли задается `in`? или надо как `out` задать через `System.in(in)`?
5)И там в тестах есть папка resources, в ней нужно тестовые файлы хранить?
6)и можно как-то на гите помечать, что код косячный? например я работаю с компа, а хочу продолжить писать код на ноуте, для этого заливаю на гит и дальше кидаю на новбук
7) там после небольшой правки main у меня запускается нормально, но текст не обрабатывается как нужно

**Comment by Suntrie** [comment]
> после огромной стены текста, которую я вам скинул, я вроде разобрался, но все равно не уверен.
> Тесты не работают. Я вообще не знаю, будет ли все что я написал работать, но я залью на гит, может вы что-то скажете.)
> 1)у меня архитектура немного отличается от той, что вы предлагали. Допустима ли она?
> 2)range нигде не вызывается, но ето норма? он все равно будет работать при запуске парсера?
> 3)везде ли я добавил try catch? я, скорее всего, не очень в них разобрался, поэтому испытываю затруднения
> 4) в классе обработки файлов правильно ли задается `in`? или надо как `out` задать через `System.in(in)`?
> 5)И там в тестах есть папка resources, в ней нужно тестовые файлы хранить?
> 6)и можно как-то на гите помечать, что код косячный? например я работаю с компа, а хочу продолжить писать код на ноуте, для этого заливаю на гит и дальше кидаю на новбук
> 7) там после небольшой правки main у меня запускается нормально, но текст не обрабатывается как нужно

1. Допустима, за исключением того, что я не поняла, зачем Вам нужно хранить такой объем дублирующейся информации в Config (поправьте меня, но вроде за имена флагов непосредственно в консоли отвечает только опция name, а имена переменных здесь не причем;

2. Это можно проверить, задав конфигурацию через Edit configurations (см. пояснения в файле "Вопросы и ответы" и запустив с ней проект - Run -> Debug...);

3. Я, наверное, не очень поняла, почему Вы вот эту проверку `if (!w && !c)` осуществляете только в случае уже полученного исключения (вроде, рискуете не дойти). Кроме этого, пока вроде не проверяются в принципе (по значениям) некорректные диапазоны;

4. Можно по-разному,  здесь важнее другое - во-первых, если Вы закрываете объект-враппер, вложенные потоки тоже закрываются (делать close, а потом выходить через try-with-resources, наверное, не очень имеет смысл),  [для ситуации с System.in так делать не стоит](https://coderanch.com/wiki/678613/Don-close-Scanner-tied-System). Для System.out нужно будет после завершения работы вернуть на место исходный поток;

5. Да;

6. //UNDER CONSTRUCTION (что-нибудь заметное);

7. ?

**Comment by Suntrie** [comment]
К базовому треду:

1. Актуально (где-то забыли удалить required);

2. Наверное, но в текущей реализации непонятно, почему Вы в итоге вместо файлов берете пути к ним (и даже если так - для работы с путями предназначены классы Paths, Path);

3. V

4. -

5. Прокомментировала в ответе (1,3);

6. Прокомментировала в ответе (1);

7. -

8. - 

9. V

10. Прокомментировала в ответе (4);
___________

a. (minor) Про правила именования пакетов и методов в Java можно посмотреть, например, [здесь](https://google.github.io/styleguide/javaguide.html);

b.  Что-то пошло не так с областями видимости переменных в ReaderAndWriter (либо выбранные области нужно объяснить). Кроме этого, Cutter-> checker -  это действительно интерфейсный метод, а не метод реализации?

c. Делать вот так: `catch (IOException e) {
            e.printStackTrace(); //no sense
        }` не имеет смысла, это соответствует стандартной обработке -  в подобном случае можно просто оставить throws. Кроме этого,  все же в большинстве случаев блоки try стремятся сделать максимально маленькими по размеру, это помогает улучшить читаемость кода;

d. Действительно ли в ситуациях, когда у Вас opening символ вне строки, программа должна фиксировать очередную строку целиком?
